---

- name: Create machines configuration directory
  ansible.builtin.file:
    name: '{{ vagrant_machines_directory }}'
    state: directory

- name: Generate Vagrant file
  ansible.builtin.template:
    src: Vagrantfile.j2
    dest: '{{ vagrant_machines_directory }}/Vagrantfile'
    mode: '644'

- name: Retrieve machines IDs
  ansible.builtin.set_fact:
    vagrant_machines: '{{ vagrant_machines|set_vagrant_machines_ids }}'

- name: Create machines metadata directories
  ansible.builtin.file:
    name: '{{ vagrant_machines_directory }}/.vagrant/machines/{{ item.name }}/{{ item.provider }}'
    state: directory
  loop: '{{ vagrant_machines }}'
  loop_control:
    label: '{{ item.name }}'

- name: Update machines IDs file
  ansible.builtin.copy:
    dest: '{{ vagrant_machines_directory }}/.vagrant/machines/{{ item.name }}/{{ item.provider }}/id'
    content: '{{ item.uuid }}'
    force: true
  loop: '{{ vagrant_machines }}'
  loop_control:
    label: '{{ item.name }}'

...
