---

- name: Create machines configuration directory
  file:
    name: '{{ vagrant_machines_directory }}'
    state: directory

- name: Generate Vagrant file
  template:
    src: Vagrantfile.j2
    dest: '{{ vagrant_machines_directory }}/Vagrantfile'
    mode: 0644

- name: Detect machines IDs
  set_fact:
    vagrant_machines: '{{ vagrant_machines|set_vagrant_machines_ids }}'

- name: Create machines metadata directories
  file:
    name: '{{ vagrant_machines_directory }}/.vagrant/machines/{{ item.name }}/{{ item.provider }}'
    state: directory
  loop: '{{ vagrant_machines }}'
  loop_control:
    label: '{{ item.name }}'

- name: Update machines IDs file
  copy:
    dest: '{{ vagrant_machines_directory }}/.vagrant/machines/{{ item.name }}/{{ item.provider }}/id'
    content: '{{ item.uuid }}'
    force: yes
  loop: '{{ vagrant_machines }}'
  loop_control:
    label: '{{ item.name }}'
