---

- ansible.builtin.assert:
    that:
      - vagrant_snapshots is defined

- name: Retrieve snapshots
  ansible.builtin.command:
    vagrant snapshot list {{ item.key }}
  args:
    chdir: '{{ vagrant_machines_directory }}'
  changed_when: false
  check_mode: false
  loop_control:
    label: '{{ item.key }}'
  register: vagrant_snapshot_list
  with_dict: '{{ vagrant_snapshots }}'

- name: Take snapshots
  ansible.builtin.command:
    vagrant snapshot take {{ item.item.key }} {{ item.item.value }}
  args:
    chdir: '{{ vagrant_machines_directory }}'
  loop: '{{ vagrant_snapshot_list.results|default([]) }}'
  loop_control:
    label: '{{ item.item.key }} snapshot {{ item.item.value }}'
  when: "' {{ item.item.value }} ' not in item.stdout"

...
